name: Deploy Production

on:
  push:
    branches: [ release ]
  
jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: ${{ secrets.PROD_DEPLOY_HOST }}
        username: ${{ secrets.PROD_DEPLOY_USERNAME }}
        api-token: ${{ secrets.PROD_DEPLOY_TOKEN }}
        domain-name: ${{ secrets.PROD_DEPLOY_DOMAIN }}
